# Generated by Django 5.2.11 on 2026-02-06 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_stocksnapshot'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='locations.location'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='inventory.item'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', 'location', 'occurred_at'], name='inventory_i_item_id_415522_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['location', 'occurred_at'], name='inventory_i_locatio_7f2005_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['item', 'location'], name='inventory_s_item_id_24723b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['location', 'item'], name='inventory_s_locatio_b8661a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocksnapshot',
            constraint=models.UniqueConstraint(fields=('item', 'location'), name='uq_stock_item_location'),
        ),
    ]
