# Generated by Django 5.2.11 on 2026-02-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement_location_stocksnapshot_location_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='locations.location'),
        ),
    ]
