# Generated by Django 5.2.11 on 2026-02-06 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_location_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='void_of',
            field=models.OneToOneField(blank=True, help_text='Si este movimiento es el reverso de otro, aquí va el original.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_by_movement', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='void_reason',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='locations.location'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['is_void', 'occurred_at'], name='inventory_i_is_void_36e11a_idx'),
        ),
    ]
