# Generated by Django 5.2.11 on 2026-02-07 04:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorymovement_is_void_inventorymovement_void_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksnapshot',
            name='reserved',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
