# Generated by Django 5.2.11 on 2026-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('MRO_DAILY_REPORT', 'MRO Daily Report')], max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, default='', max_length=256)),
                ('subject', models.CharField(blank=True, default='', max_length=256)),
                ('error', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'created_at'], name='audit_notif_kind_5a5a6a_idx'), models.Index(fields=['kind', 'key'], name='audit_notif_kind_e78065_idx'), models.Index(fields=['cooldown_until'], name='audit_notif_cooldow_567d12_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='uq_notification_kind_key')],
            },
        ),
    ]
