# Generated by Django 5.2.11 on 2026-02-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'warehouse',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='warehouse_code_0bdf05_idx'), models.Index(fields=['name'], name='warehouse_name_d8d877_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.warehouse')),
            ],
            options={
                'db_table': 'location',
                'ordering': ['warehouse__code', 'code'],
                'indexes': [models.Index(fields=['warehouse', 'code'], name='location_warehou_5de155_idx'), models.Index(fields=['code'], name='location_code_c48836_idx')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'code'), name='uq_location_warehouse_code')],
            },
        ),
    ]
